apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  containers:
  - name: keycloak
    image: quay.io/keycloak/keycloak:latest
    args: ["start-dev"]
    ports:
      - containerPort: 8080
    env:
      - name: KEYCLOAK_ADMIN
        value: "admin"
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: "admin123"
